version: '3'

services:
  api:
    build: ./api
    container_name: api
    tty: true
    environment:
      NODE_PATH: /usr/local/lib/node_modules
    links:
      - db
    volumes:
      - ./api:/api
    ports:
      - "80:80"

  db:
    build: ./db
    container_name: db
    tty: true
    volumes:
      - ./db:/db
    ports:
      - "5984:5984"
